### ISSUE TITLE
Allegro build scripts for VS 2022

### ISSUE THREAD

**Issue by WernherVonData** [liballeg/allegro_winpkg#13]
Hi,
I started building allegro lately and I checked how the build works for Windows. I see there is a build of dependencies for VS 2022, but there are no similar scripts for building the whole allegro for VS 2022 - I created them on my side and thought maybe to add them here as well.

Can I create a PR? If I'm not mistaken, I can't push to this repo without access.

**Comment by SiegeLord** [comment]
Sure, you can send a pull request. Not sure how I missed those (there's the dependency scripts, but not the main allegro somehow).

**Comment by WernherVonData** [comment]
Is there some kind of permission required? I can't push a branch to this repo.

**Comment by SiegeLord** [comment]
Here's a tutorial you could follow: https://github.com/firstcontributions/first-contributions

**Comment by WernherVonData** [comment]
Thanks, will take a look, this is my first time contributing to something else than my own repo on github.

**Comment by WernherVonData** [comment]
PR is created - forgot to add reviewers and looks like I'm unable to do it now...
