### ISSUE TITLE
Small opusfile version mistake in 1.14.0 release asset 

### ISSUE THREAD

**Issue by geecab** [liballeg/allegro_winpkg#15]
Hi there,

I downloaded the allegro_winpkg-1.14.0.zip asset from here:
        https://github.com/liballeg/allegro_winpkg/releases
        Releases -> 1.14.0 -> Assets -> Source code(zip)

I built the everything on Windows 10 using build_deps_msvc2022_64.bat script.

I noticed the opusfile project didn't get built.

To make things build I had to rename this directory:
    C:\my_work\universal\opusfile-0.12
to this:
    C:\my_work\universal\opusfile-0.11

If I clone the allegro_winpkg repos and build, everything builds fine. The problem is just with the  allegro_winpkg-1.14.0.zip asset.

Nothing major I know, just thought I'd mention it :)

**Comment by SiegeLord** [comment]
It's a typo in the build script, thanks for reporting this!
