### ISSUE TITLE
Clang target ?

### ISSUE THREAD

**Issue by jacmoe** [liballeg/allegro_winpkg#9]
I switch the platform toolset in Visual Studio to `LLVM (clang-cl)` and noticed that the Allegro Nuget packages only contains `v141` and `v142`.

I *could* maybe look into this myself, but I have no clue (not yet anyway) about what such an endeavor entails.

It would be very nice, though!

Clang support is a fairly recent thing in Visual Studio - https://docs.microsoft.com/en-us/cpp/build/clang-support-msbuild?view=msvc-160 - so I just wanted to let you know that this is something that is possible, and also wanted :)

EDIT:
I believe it can be done by adding `clang-cl` to the list of toolsets:

```
parser.add_argument('--toolchains', default='v141,v142,clang-cl')
```

**Comment by SiegeLord** [comment]
Thanks! I'll keep this in mind when making the release packages!

**Comment by SiegeLord** [comment]
The Allegro 5.2.7 and AllegroDeps 1.12 NuGet packages have clang support.

FYI, the toolchain is actually called `ClangCL`.

**Comment by jacmoe** [comment]
I have to say I am so very pleased! Thank you 😄 ❤️ I can't wait to try this! 👯 
Edit: and it works wonderfully :) I got a couple new compiler errors to fix that neither GCC nor VC caught. Nice!
